version: '3'
services:
    backend:
        image: node:8
        ports:
            - "3001:3001"
        volumes:
            - ../backend:/usr/src/app
            - ../datas:/usr/src/datas
        working_dir: /usr/src/app
        command: bash -c "npm i && npm start"
        links:
            - "frontend"
    frontend:
        build: ../frontend
        ports:
          - "5000:5000"
        volumes:
          - ../frontend:/usr/src/app
        working_dir: /usr/src/app
        command: bash -c "npm i && npm run build && serve -s build"
